[package]
name = "teph_amrex"
version = "0.1.0"
edition = "2024"

[dependencies]
tephrite_rs = { git = "https://github.com/InsightCenterNoodles/tephrite_rs.git", rev = "8937c9fc07e58efd65e1704001c1b2b215abc40f" }
amrex_rs = { git = "https://github.com/nicholasbl/amrex_rs.git", rev = "7d8f7292f0c14c37e2de0faaa564cf1da410d8c6" }
bevy = "0.18.1"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
crossbeam-queue = "0.3"
memmap2 = "0.9"
mini-moka = "0.10"
serde = { version = "1", features = ["derive"] }
toml = "0.9"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
